version: '3'

services:
  #usage
  #$docker-compose run --rm gradle buildAgent buildCoveragePluginDev
  gradle:
    image: gradle:5.5.1-jdk8
    volumes:
      - ../:/home/gradle/project
      - drill_gradle_data:/home/gradle/.gradle
    user: root
    working_dir: /home/gradle/project
    entrypoint: gradle
    environment:
      KONAN_DATA_DIR: /home/gradle/.gradle/konan
      GRADLE_OPTS: -Dorg.gradle.daemon=false

volumes:
    drill_gradle_data:
